In [1]:
import sys
print(sys.executable)

e:\Web Projects\.venv\Scripts\python.exe


In [2]:
%pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 310.6 kB/s eta 0:00:38
   - -------------------------------------- 0.5/12.3 MB 310.6 kB/s eta 0:00:38
   - -------------------------------------- 0.5/12.3 MB 310.6 kB/s eta 0:00:38
   - -------------------------------------- 0.5/12.3 MB 310.6 kB/s eta 0:00:38
   -- ------------------------------------- 0.8/12.3 MB 335.4 kB/s eta 0:00:35
   -- ------------------------------------- 0


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [3]:
print(np.__version__)

2.4.6


In [4]:
my_list = np.array([1,2,3,4,5])
print(my_list * 2)

[ 2  4  6  8 10]


In [5]:
arr = np.array([[1,2,3],[3,4,5]])
print(arr.ndim)

2


In [6]:
arr = np.array([[1,2,3],[3,4,5]])
print(arr.shape)
print(arr[0,1])

(2, 3)
2


In [8]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
#array[start:end:step] end is exclusive
print(arr[2:1:-1])
print(arr[2:,::-2])

[[ 9 10 11 12]]
[[12 10]
 [16 14]]


In [20]:
arr = np.array([1.01, 2.92, 3.3])
print(arr % 3)
print(np.sqrt(arr))
print(np.ceil(arr))
print(np.pi)

[1.01 2.92 0.3 ]
[1.00498756 1.70880075 1.81659021]
[2. 3. 4.]
3.141592653589793


In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 ** arr2)

[  1  32 729]


In [26]:
scores = np.array([91, 55, 100, 73, 82, 64])
print(scores == 100)
print(scores >= 60)
scores[scores < 60] = 0
print(scores)

[False False  True False False False]
[ True False  True  True  True  True]
[ 91   0 100  73  82  64]


In [28]:
arr1 = np.array([[1,2,3,4]])
arr2 = np.array([[1],[2],[3],[4]])
print(arr1.shape)
print(arr2.shape)
print(arr1 * arr2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [33]:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.sum(arr,axis = 1))

55
5.5
2.8722813232690143
8.25
[15 40]


In [10]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages < 65)]
evens = ages[ages % 2 == 0]
print(teenagers)
print(adults)
print(evens)

adults = np.where(ages >= 18, ages, 0)
print(adults)
print(ages)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[20 16 30 18 22 18 20]
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]
[[21 17 19 20 16 30 18 65]
 [39 22 15 99 18 19 20 21]]


In [18]:
rng = np.random.default_rng()

print(rng.integers(1, 7, 3))
print(rng.integers(1, 7, (3,2)))

[3 4 2]
[[4 4]
 [3 2]
 [3 4]]


In [ ]:
rng = np.random.default_rng(seed = 1)

print(rng.integers(1, 7, (3,2)))
print(np.random.uniform(1, 10))

[[3 4]
 [5 6]
 [1 1]]


In [27]:
rng = np.random.default_rng()
arr = np.array(["apple", "orange", "banana", "coconut", "pineapple"])
fruits = rng.choice(arr,(3,2))
print(fruits)

[['coconut' 'banana']
 ['orange' 'coconut']
 ['orange' 'pineapple']]


In [3]:
arr = np.arange(5)
print(arr)

lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[0 1 2 3 4]
[  0.  25.  50.  75. 100.]


In [7]:
# 1-D array 
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
                one_dim_arr, # the array to be reshaped
               (2,3) # dimensions of the new array
              )
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)
print(multi_dim_arr.size)

[[1 2 3]
 [4 5 6]]
6


In [10]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]
