In [1]:
import sys
print(sys.executable)

e:\Web Projects\.venv\Scripts\python.exe


In [2]:
%pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 310.6 kB/s eta 0:00:38
   - -------------------------------------- 0.5/12.3 MB 310.6 kB/s eta 0:00:38
   - -------------------------------------- 0.5/12.3 MB 310.6 kB/s eta 0:00:38
   - -------------------------------------- 0.5/12.3 MB 310.6 kB/s eta 0:00:38
   -- ------------------------------------- 0.8/12.3 MB 335.4 kB/s eta 0:00:35
   -- ------------------------------------- 0


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.4.6


In [6]:
my_list = np.array([1,2,3,4,5])
print(my_list * 2)

[ 2  4  6  8 10]


In [11]:
arr = np.array([[1,2,3],[3,4,5]])
print(arr.ndim)

2


In [18]:
arr = np.array([[1,2,3],[3,4,5]])
print(arr.shape)
print(arr[0,1])

(2, 3)
2


In [32]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
#array[start:end:step] end is exclusive
print(arr[2:1:-1])
print(arr[2:,1:3])

[[ 9 10 11 12]]
[[10 11]
 [14 15]]
