In [1]:
import numpy as np

In [11]:
mat = np.array([[1,2,3,4],[5,6,7,8]])
vec = np.array([2,2,2,2])
print(mat @ vec)

[20 52]


In [ ]:
def get_index_first_non_zero_value_from_column(M, column, starting_row):
    # Get the column array starting from the specified row
    column_array = M[starting_row:,column]
    for i, val in enumerate(column_array):
        # Iterate over every value in the column array. 
        # To check for non-zero values, you must always use np.isclose instead of doing "val == 0".
        if not np.isclose(val, 0, atol = 1e-5):
            # If one non zero value is found, then adjust the index to match the correct index in the matrix and return it.
            index = i + starting_row
            return index
    # If no non-zero value is found below it, return -1.
    return -1

In [9]:
def swap_rows(M, row_index_1, row_index_2):
    # Copy matrix M so the changes do not affect the original matrix. 
    M = M.copy()
    # Swap indexes
    M[[row_index_1, row_index_2]] = M[[row_index_2, row_index_1]]
    return M

In [20]:
A = np.array([[0,1,0],[1,2,3], [0,0,5]])
B = np.array([[1], [2], [4]])
aug_M = np.hstack((A,B))
first_pivot = get_index_first_non_zero_value_from_column(aug_M,0,0)
if np.isclose(aug_M[0,0],0)==True:
    aug_M = swap_rows(aug_M,0,first_pivot)
print(aug_M)
print(aug_M.shape)

[[1 2 3 2]
 [0 1 0 1]
 [0 0 5 4]]
(3, 4)


In [ ]:
for i in reversed(range(3)):
    print(i)

2
1
0


: 